### ISSUE TITLE
Dataloader of SCANNET is not provided.

### ISSUE THREAD

**Issue by liujiaheng** [pleaseconnectwifi/PNAL#5]
![image](https://user-images.githubusercontent.com/27964642/137702282-2b89488b-bc8f-471e-9553-9992be519483.png)

Hi, in "PANL_dgcnn.py", the dataloader of scannet is not provided.

**Comment by liujiaheng** [comment]
![image](https://user-images.githubusercontent.com/27964642/138197251-6ea0d9cb-ac36-4b95-b925-91dc13495eaf.png)
![image](https://user-images.githubusercontent.com/27964642/138197284-aed3b4ed-89c9-4aea-92ec-2a0af9496980.png)
``util.io_utils'' and ``make_NL_S3DIS.py'' are also not provided. 


Thanks for your nice work and code.

**Comment by Pixie412** [comment]
Hi @liujiaheng, I encountered same problem of training very slow. It takes around 30 minutes to train 100 iters in the cleaning stage. Did you managed to solve this problem?

**Comment by liujiaheng** [comment]
No
