### ISSUE TITLE
S3DIS with different noise rates

### ISSUE THREAD

**Issue by daoyuan98** [pleaseconnectwifi/PNAL#7]
Hi, thank you for your great work! 

I saw there is processed S3DIS with 60% noise rate. To follow your work, would you like to release the datasets (or the generation script) with different noise levels?

Thanks!

**Comment by pleaseconnectwifi** [comment]
Many thanks for your attention to our work! I just added the scripts for making label noise under different noise type and noise rate settings and the clustering.
